version: '3.7'
services: 
    fastapi:
        container_name: fastapi
        build:
            context: ./fastapi/
            dockerfile: Dockerfile
        volumes:
            - ./fastapi/app:/app:ro
        environment:
            - WEB_CONCURRENCY=1
            - PORT=8080
    react:
        container_name: react
        build: 
            context: ./react/
            dockerfile: Dockerfile
        volumes:
            - ./react/app:/app
            - /app/node_modules
        command: npm start
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    nginx:
        depends_on:
            - fastapi
            - react
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx:/etc/nginx/templates
        ports:
            - 8099:80
        
